dev:
  propel:
    param:
      classname: DebugPDO
      
cache:
  propel:
    class: sfPropelDatabase
    param:
      classname: DebugPDO
      
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'pgsql:host=localhost;dbname=jobeet'
      username: jobeet
      password: password
      encoding: utf8
      persistent: true
      pooling: true
