#!/bin/sh

sudo -u postgres psql -U postgres template1 --command="create user phppgadmin password 'MN1@njvr' createdb createuser;"
sudo -u postgres createdb --owner phppgadmin jobeet

./symfony test-unit
