<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/01/11 12:49:46
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 5,
  'app_max_jobs_on_category' => 15,
));
