<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/01/11 12:49:46

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'pgsql:host=localhost;dbname=jobeet',
  'username' => 'phppgadmin',
  'password' => 'MN1@njvr',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
